---
title: "Dashboard de ações"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
# dashboard
library(flexdashboard)

# Manipular as tabelas
library(dplyr)


# Gráficos
library(ggplot2)
library(plotly)

# pegar dados financeiros
library(tidyquant)
```

Column {.sidebar}
----------------------------------------------------------------------

```{r}
selectInput(
  "ticker",
  "Escolha o ticker: ",
  choices = c("PETR4.SA", "BBAS3.SA", "VALE3.SA", "WEGE3.SA")
)
```



```{r download}

dados_tbl <- reactive({
 tq_get(input$ticker) 
}) 
```



Column {data-width=500}
-----------------------------------------------------------------------

### Cotações

```{r}
renderDataTable({
  dados_tbl() %>% 
  select(date, adjusted) %>% 
  arrange(desc(date))})

```

Column {data-width=500}
-----------------------------------------------------------------------


### Gráfico 1
```{r}
renderPlotly({
  g <- tq_get("PETR4.SA") %>% 
  ggplot(aes(x = date, y = adjusted)) +
  geom_line()

ggplotly(g)
})
```

### Grafico 2
```{r}
renderPlotly({
  tq_get(c("PETR4.SA", "BBAS3.SA", "VALE3.SA", "WEGE3.SA")) %>% 
  group_by(symbol) %>%
  mutate (cotacao = (adjusted - mean(adjusted))/sd(adjusted)) %>%
    ungroup() %>%
  ggplot(aes(x = date, y = cotacao, color = symbol)) +
  geom_line()

})
```
 
